sensor:
  - platform: command_line
    name: kitchen_fan_light
    command: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.1.37 '/home/pi/bluetooth/get_kitchen_fan_light.sh'"

light:
  - platform: template
    lights:
      kitchen_fan_light:
        unique_id: kitchen_fan_light
        friendly_name: "Fläktlampan"
        level_template: "{{ states('sensor.kitchen_fan_light')|int }}"
        value_template: "{{ states('sensor.kitchen_fan_light')|int > 0 }}"
        turn_on:
          - service: shell_command.set_kitchen_fan_light
            data_template:
              value: 255
          - delay: 2
          - service: homeassistant.update_entity
            entity_id: sensor.kitchen_fan_light
        turn_off:
         - if:
             condition: state
             entity_id: light.kitchen_fan_light
             state: "on"
           then:
             - service: shell_command.set_kitchen_fan_light
               data:
                 value: 0
             - delay: 2
             - service: homeassistant.update_entity
               entity_id: sensor.kitchen_fan_light
        set_level:
          - service: shell_command.set_kitchen_fan_light
            data_template:
              value: "{{ brightness }}"
          - delay: 2
          - service: homeassistant.update_entity
            entity_id: sensor.kitchen_fan_light

shell_command:
  set_kitchen_fan_light: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.1.37 "/home/pi/bluetooth/set_kitchen_fan_light.sh {{ value }}"
